project:
  type: website

website:
  title: "DL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Aplications
      - href: intro_pytorch.qmd
        text: Intro Pytorch
      - href: tensor_playground.qmd
        text: Playground
        
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

