on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Clean up gh-pages branch
        run: |
          # Configure git so that commits can be made by the Action
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Attempt to clone the gh-pages branch; if it doesn't exist, create it
          if git clone --branch gh-pages --depth 1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages; then
            echo "gh-pages branch cloned."
          else
            echo "gh-pages branch does not exist. Creating a new one."
            mkdir gh-pages && cd gh-pages
            git init
            git checkout -b gh-pages
            cd ..
          fi
          
          # Remove all files from the branch
          cd gh-pages
          git rm -rf . || true
          rm -rf *
          
          # Commit and push the removal
          git commit -m "Clean up gh-pages branch" || echo "Nothing to commit"
          git push origin gh-pages
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
